wikiWeapDict = {
   'key' : ['type', 'range', 'dmg-type', 'base-dmg'],
   'battle-axe' : ['melee', 'range', 'bludgeoning/slashing', 'base-dmg'],
   'bludgeon ' : ['type', 'range', 'dmg-type', 'base-dmg'],
   'club ' : ['type', 'range', 'dmg-type', 'base-dmg'],
   'flail ' : ['type', 'range', 'dmg-type', 'base-dmg'],
   'flanged-mace ' : ['type', 'range', 'dmg-type', 'base-dmg'],
   'horseman\'s-pick' : ['type', 'range', 'dmg-type', 'base-dmg'],
   'mace ' : ['type', 'range', 'dmg-type', 'base-dmg'],
   'morning-star ' : ['type', 'range', 'dmg-type', 'base-dmg'],
   'quarterstaff ' : ['type', 'range', 'dmg-type', 'base-dmg'],
   'swords' : ['the following are swords and other blades'],
   'arming-sword ' : ['type', 'range', 'dmg-type', 'base-dmg'],
   'dagger ' : ['type', 'range', 'dmg-type', 'base-dmg'],
   'estoc ' : ['type', 'range', 'dmg-type', 'base-dmg'],
   'falchion ' : ['type', 'range', 'dmg-type', 'base-dmg'],
   'katana' : ['type', 'range', 'dmg-type', 'base-dmg'],
   'knife' : ['type', 'range', 'dmg-type', 'base-dmg'],
   'longsword' : ['type', 'range', 'dmg-type', 'base-dmg'],
   'rapier' : ['type', 'range', 'dmg-type', 'base-dmg'],
   'sabre' : ['type', 'range', 'dmg-type', 'base-dmg'],
   'shortsword' : ['type', 'range', 'dmg-type', 'base-dmg'],
   'ulfberht' : ['type', 'range', 'dmg-type', 'base-dmg'],
   }
